export const SET_WORD = "SET_WORD";
export const PUSH_LETTER_TO_INPUTBOXES = "PUSH_LETTER_TO_INPUTBOXES";
export const SET_CURRENT_ATTEMPT_INDEX = "SET_CURRENT_ATTEMPT_INDEX";
export const POP_LETTER_FROM_INPUTBOXES = "POP_LETTER_FROM_INPUTBOXES";
export const SET_LETTER_CLASSES = "SET_LETTER_CLASSES";
export const SET_GAME_OVER = "SET_GAME_OVER";
export const RESET_WORDLE_STATE = "RESET_WORDLE_STATE";
